spring:
  application:
    name: workout-tracker
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
